# Generated by Django 2.2.3 on 2019-07-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190715_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
